# -*- coding: utf-8 -*-
"""Simpsons_method

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1334sK4f39fGfgsN4gItEWzDMs4BQuv15
"""

# Commented out IPython magic to ensure Python compatibility.
import sympy as sym
from sympy.abc import x
from scipy.integrate import quad
from math import sin, cos, tan, log, e, pi
import numpy as np
from random import randint
import matplotlib.pyplot as plt
# %matplotlib inline

func = input('Enter the function: ')
f = sym.lambdify(x, func)
a = int(input('Enter the start of the interval: '))
b = int(input('Enter the end of the interval: '))

def Simpsons_method(f, a, b):
    def find_polynomial(x1, x2, x3, y1, y2, y3):
        a = (x1*(y3-y2) + x2*(y1-y3) + x3*(y2-y1))/((x1-x2)*(x1-x3)*(x2-x3))
        b = ((y2-y1)/(x2-x1)) - a*(x1+x2)
        c = y1 - a*x1**2 - b*x1
        return sym.lambdify(x, sym.sympify('{}*x**2 + {}*x + {}'.format(a, b, c)))
    n = randint(5, 50)
    if n % 2 != 0:
        n += 1
    x_val = np.linspace(a, b, n+1)
    dx = (b-a)/n
    area_of_parab = 0
    for i in range(0, len(x_val)-2, 2):
        x_1, x_2, x_3 = x_val[i], x_val[i+1], x_val[i+2] 
        pol_func = find_polynomial(x_1, x_2, x_3, f(x_1), f(x_2), f(x_3))
        area_of_parab += quad(pol_func ,x_1, x_3)[0]
        
    return(area_of_parab)   
Simpsons_method(f, a, b)

def Simpsons_method_graph(f,a,b):
    array = np.linspace(a, b, 50)
    plt.plot(array, f(array), color='black')
    n = randint(5, 50)
    if n % 2 != 0:
        n += 1
    x_val = np.linspace(a, b, n+1)
    area_of_parab = 0
    def find_polynomial(x1, x2, x3, y1, y2, y3):
      a = (x1*(y3-y2) + x2*(y1-y3) + x3*(y2-y1))/((x1-x2)*(x1-x3)*(x2-x3))
      b = ((y2-y1)/(x2-x1)) - a*(x1+x2)
      c = y1 - a*x1**2 - b*x1
      return sym.lambdify(x, sym.sympify('{}*x**2 + {}*x + {}'.format(a, b, c)))

    for i in range(0, len(x_val)-2, 2):
      x_1, x_2, x_3 = x_val[i], x_val[i+1], x_val[i+2]
      pol_func = find_polynomial(x_1, x_2, x_3, f(x_1), f(x_2), f(x_3))
      area_of_parab += quad(pol_func ,x_1, x_3)[0]
      array = np.linspace(x_val[i], x_val[i+2], 50)
      plt.fill_between(array, pol_func(array)) 
     

Simpsons_method_graph(f,a,b)