# -*- coding: utf-8 -*-
"""Trapezoid_modified.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVDLusBy2qCHm5t-KbgkN9XBWwnNq4qh
"""

# Commented out IPython magic to ensure Python compatibility.
import sympy as sym
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from sympy.abc import x
from sympy import *
x = sym.symbols('x')

# func = input("Enter a Function: ")
# initial_point = int(input("Enter starting point: "))
# end_point = int(input("Enter ending point: "))
# n = int(input("Number of intervals: "))
def Trapezoid(function:str,initial_point:int,end_point:int,n:int) ->str:
    
  function = sym.lambdify(x, function)
  dx = (end_point - initial_point)/n

  A = 1/2 *(function(initial_point) + function(end_point))
  for i in range(1, n):
      A = A + function(initial_point + i*dx)
  Area = dx * A
  
  return str(Area)

# Trapezoid(function, initial_point, end_point, n)
a = Trapezoid("x**2", 0, 3.14, 10)

print(a)

# def Trapezoid_graph(function,initial_point,end_point,n):
#     X = np.linspace(initial_point,end_point,100)
#     x = np.linspace(initial_point,end_point,n+1)
#     Y = function(X)
#     plt.figure(figsize = (15,10))
#     plt.plot(X,Y, color='black', linewidth=2, markersize=50)

#     for i in range(n):
#         initial_point = [x[i],x[i],x[i+1],x[i+1]]
#         end_point = [0,function(x[i]),function(x[i+1]),0]
#         plt.fill(initial_point,end_point,'lightblue', edgecolor='black',alpha=1)

#     plt.title('Area under the curve, Trapezoid method')
#     plt.savefig('image.png')
# Trapezoid_graph(function,initial_point,end_point,n)